<template>
  <v-form ref="passForm" class="generate-password-page">
    <v-text-field
      density="compact"
      variant="outlined"
      v-model="localOptions.length"
      type="number"
      label="Length *"
      hide-spin-buttons
      :rules="[rules.required, rules.passwordLengthShouldBe5OrGreater]"
    />
    <v-checkbox
      label="Include digits"
      density="compact"
      v-model="localOptions.includesDigits"
    />
    <v-checkbox
      label="Include uppercase letters"
      density="compact"
      v-model="localOptions.includesUpperCase"
    />
    <v-checkbox
      label="Include special characters"
      density="compact"
      v-model="localOptions.includesSpecialChars"
    />
    <v-divider class="mb-5"></v-divider>
    <v-btn
      color="success"
      density="default"
      variant="outlined"
      prepend-icon="mdi-autorenew"
      no-cap
      @click="generate"
      >Generate random password</v-btn
    >
    <v-container
      fluid
      v-if="generated !== ''"
      class="d-flex mt-5 align-center justify-space-between generated-text-cont"
    >
      <span>{{ generated }}</span>
      <v-icon @click="copyGeneratedPassword">mdi-content-copy</v-icon>
    </v-container>
    <v-snackbar v-model="copied" timeout="1500">
      Password copied to clipboard
    </v-snackbar>
  </v-form>
</template>

<script lang="ts" setup>
import { onMounted, ref, watch } from "vue";
import { generatePassword } from "../utils/generate-password";
import useUiStore from "../store/ui.store";
import { autoGenerateDefaultOptions } from "../utils/constants";
import { rules } from "../utils/validation";

const ui = useUiStore();

const localOptions = ref(autoGenerateDefaultOptions);
const generated = ref("");
const copied = ref(false);

function generate() {
  const result = generatePassword(localOptions.value);
  generated.value = result;
}

async function copyGeneratedPassword() {
  await window.navigator.clipboard.writeText(generated.value);
  copied.value = true;
}

watch(
  localOptions,
  (_new: any) => {
    ui.setAutoGenerateOptions(_new);
  },
  { deep: true }
);

onMounted(() => {
  localOptions.value = { ...ui.generateOptions };
});
</script>

<style scoped>
.generate-password-page {
  width: 40%;
}

.generated-text-cont {
  background-color: #1e1e1e;
  width: 100%;
  color: white;
  word-break: break-all;
  border-radius: 5px;
}

@media (max-width: 900px) {
  .generate-password-page {
    width: 60%;
  }
}
@media (max-width: 700px) {
  .generate-password-page {
    width: 90%;
  }
}
</style>
