import type { PossibleEntryStatus } from "./_types";

const isDevMode = import.meta.env.MODE === "development";
const useProdUrlAnyway =
  import.meta.env.VUE_APP_USE_PROD_URL &&
  import.meta.env.VUE_APP_USE_PROD_URL === "1";

const devUrl = "http://localhost:5000";
const prodUlr = "https://yahya-8csr.onrender.com";

export const BACKEND_BASE_URL =
  isDevMode && !useProdUrlAnyway ? devUrl : prodUlr;

export const AUTH_UI_URL = "https://account.yahyasalimi.com";
export const SITE_URL = window.location.origin;

// generate password
export const autoGenerateDefaultOptions = {
  length: 12,
  includesDigits: true,
  includesUpperCase: true,
  includesSpecialChars: false,
};

// Filtering
export const defaultFilterObject = {
  search: "",
  status: "" as PossibleEntryStatus | "",
  category: "",
};
