export const autoGenerateDefaultOptions = {
  length: 12,
  includesDigits: true,
  includesUpperCase: true,
  includesSpecialChars: false,
};

const state = {
  notification: "",
  error: "",
  expandedCategories: [],
  autoGenerateOptions: autoGenerateDefaultOptions,
  showMoreFilters: false,
};

const getters = {
  notification: (state) => state.notification,
  error: (state) => state.error,
  expandedOnes: (state) => state.expandedCategories,
  generateOptions: (state) => state.autoGenerateOptions,
  showMoreFilters: (state) => state.showMoreFilters,
};

const mutations = {
  setNotification: (state, notif) => (state.notification = notif),
  setError: (state, msg) => (state.error = msg),
  setExpandedCategories: (state, ec) => {
    state.expandedCategories = ec;
  },
  setAutoGenerateOptions: (state, options) => {
    state.autoGenerateOptions = { ...state.autoGenerateOptions, ...options };
  },
  setShowMoreFilters: (state, showMore) => {
    state.showMoreFilters = showMore;
  },
};

const actions = {};

export default {
  actions,
  getters,
  mutations,
  state,
};
