export const autoGenerateDefaultOptions = {
  length: 12,
  includesDigits: true,
  includesUpperCase: true,
  includesSpecialChars: false,
};

const state = {
  notification: "",
  error: "",
  expandedCategories: [],
  autoGenerateOptions: autoGenerateDefaultOptions,
  contentFetchedForTheFirstTime: false,
  viewType: "card",
};

const getters = {
  notification: (state) => state.notification,
  error: (state) => state.error,
  expandedOnes: (state) => state.expandedCategories,
  generateOptions: (state) => state.autoGenerateOptions,
  contentAlreadyFetched: (state) => state.contentFetchedForTheFirstTime,
  isCardView: (state) => state.viewType === "card",
  isTreeView: (state) => state.viewType === "tree",
};

const mutations = {
  setNotification: (state, notif) => (state.notification = notif),
  setError: (state, msg) => (state.error = msg),
  setExpandedCategories: (state, ec) => {
    state.expandedCategories = ec;
  },
  setAutoGenerateOptions: (state, options) => {
    state.autoGenerateOptions = { ...state.autoGenerateOptions, ...options };
  },
  setContentAlreadyFetched: (state, fetched) => {
    state.contentFetchedForTheFirstTime = fetched;
  },
  toggleCardView: (state) => {
    if (state.viewType === "card") {
      state.viewType = "tree";
    } else {
      state.viewType = "card";
    }
  },
};

const actions = {};

export default {
  actions,
  getters,
  mutations,
  state,
};
