<template>
  <v-form ref="passForm" class="generate-password-page">
    <v-text-field
      dense
      outlined
      v-model="localOptions.length"
      type="number"
      label="Length"
      hide-spin-buttons
      :rules="[required, isFiveOrHiger]"
    />
    <v-checkbox
      :label="includeDigitsLabel"
      dense
      v-model="localOptions.includesDigits"
    />
    <v-checkbox
      :label="includeCapitalsLabel"
      dense
      v-model="localOptions.includesUpperCase"
    />
    <v-checkbox
      :label="includeSpecialCharsLabel"
      dense
      v-model="localOptions.includesSpecialChars"
    />
    <v-divider class="mb-5"></v-divider>
    <v-btn color="success" dense outlined no-cap small @click="generate">{{
      $t("btns.generate_rand_pass")
    }}</v-btn>
    <v-container
      fluid
      v-if="generated !== ''"
      class="d-flex mt-3 align-center justify-space-between generated-text-cont"
    >
      <span>{{ generated }}</span>
      <v-icon @click="copyGeneratedPassword">mdi-content-copy</v-icon>
    </v-container>
    <v-snackbar v-model="copied" timeout="1500">
      {{ $t("main.password_copied") }}
    </v-snackbar>
  </v-form>
</template>

<script>
import { generatePassword } from "@/utils/generate-password.js";
import { mapGetters } from "vuex";
import { autoGenerateDefaultOptions } from "@/store/modules/ui";

export default {
  name: "generate-password",
  data() {
    return {
      localOptions: autoGenerateDefaultOptions,
      generated: "",
      copied: false,
    };
  },
  computed: {
    ...mapGetters(["generateOptions"]),
    includeCapitalsLabel() {
      return this.$t("main.generate_options.include_capitals");
    },
    includeDigitsLabel() {
      return this.$t("main.generate_options.include_nums");
    },
    includeSpecialCharsLabel() {
      return this.$t("main.generate_options.include_special_chars");
    },
  },
  methods: {
    generate() {
      if (this.$refs.passForm.validate()) {
        const result = generatePassword(this.localOptions);
        this.generated = result;
      }
    },
    required(value) {
      return !!value || "This field is required";
    },
    isFiveOrHiger(value) {
      return parseInt(value) >= 5 || "Password length can't be less than 5";
    },

    async copyGeneratedPassword() {
      await window.navigator.clipboard.writeText(this.generated);
      this.copied = true;
    },
  },
  watch: {
    localOptions: {
      handler(_new, _old) {
        this.$store.commit("setAutoGenerateOptions", _new);
      },
      deep: true,
    },
  },
  mounted() {
    this.localOptions = { ...this.generateOptions };
  },
};
</script>

<style scoped>
.generate-password-page {
  width: 40%;
}

.generated-text-cont {
  background-color: azure;
  width: 100%;
  word-break: break-all;
}
</style>
